(DEFUN P01 (LIST)
  (LOOP :FOR SUBLIST :ON LIST
     :IF (NULL (CDR SUBLIST))
     :RETURN SUBLIST))

(DEFUN P02 (LIST)
  (LOOP :FOR SUBLIST :ON LIST
     :IF (NULL (CDDR SUBLIST))
     :RETURN SUBLIST))

(DEFUN P03 (LIST INDEX)
  (LOOP :FOR ELEMENT :IN LIST
        :AND I :FROM 1
     :IF (= I INDEX)
     :RETURN ELEMENT))

(DEFUN P04